In [1]:
import numpy as np

In [2]:
#sigmoid activation
def sigmoid(input):
    return 1/(1 + np.exp(-input))

In [3]:
def d_sigmoid(d_init, out):
    sig = sigmoid(out)
    return d_init * sig * (1 - sig)


In [4]:
def init(layers=[4, 5, 2]):
    np.random.seed(42)

    params_w = {}
    params_b = {}

    for index in range(len(layers)-1):

        layer_num = index + 1
        in_layer_size = layers[index]
        out_layer_size = layers[index + 1]

        params_w['weight' + str(layer_num)] = np.random.randn(out_layer_size, in_layer_size) * 0.1
        params_b['bias' + str(layer_num)] = np.random.randn(out_layer_size, 1) * 0.1

    return params_w, params_b


In [77]:
def one_layer_forward_pass(input_activations, weights, bias):
    print(weights)
    y = np.transpose(weights)
    new_bias = np.transpose(bias)
#     y = weights
#     print(y.shape())
    print(y)
    
    output = np.dot(input_activations, y) + new_bias
#     output = np.array([]) 
#     print(output)
    
    activation_next = sigmoid(output)
    
    return activation_next, output

In [78]:
def forward_pass(train_X, params_w, params_b, layers=[4, 5, 2]):

    num_layers = len(layers) - 1

    activation_dict = {}
    output_dict = {}

    curr_act = train_X

    for index in range(num_layers):
#         index = 0
        layer_index = index + 1
        prev_act = curr_act     

        curr_weight = params_w["weight" + str(layer_index)]
        curr_bias = params_b["bias" + str(layer_index)]

        curr_act, curr_out = one_layer_forward_pass(prev_act, curr_weight, curr_bias)

        activation_dict["act" + str(index)] = prev_act
        output_dict["out" + str(layer_index)] = curr_out
#         return curr_act, activation_dict, output_dict
    
    return curr_act, activation_dict, output_dict

In [79]:
def train_val_split(X, Y, train_percent=0.8):

    num_points = X.shape[0]

    train_size = int(num_points * 100 * train_percent // 100)

    inds = np.arange(num_points)
    np.random.shuffle(inds)

    train_inds = inds[:train_size]
    val_inds = inds[train_size: ]

    train_X = X[train_inds, :]
    val_X = X[val_inds, :]

    train_Y = Y[train_inds]
    val_Y = Y[val_inds]

    return train_X, train_Y, val_X, val_Y

In [80]:
def parse_txt(fname, num_features=4, num_targets=1, num_points=1372):
    
    X = np.empty((num_points, num_features), dtype=float)
    Y = np.empty(num_points, dtype=int)

    with open(fname) as f:
        for index, line in enumerate(f):
            line = line.rstrip('\n')
            data = line.split(',')


            X[index, :] = np.asarray(data[:-1])
            Y[index] = np.asarray(data[num_features])

    return X, Y

In [81]:
epochs = 100
lr = 0.1

X, Y = parse_txt('data/data.txt')
train_X, train_Y, val_X, val_Y = train_val_split(X, Y)

In [82]:
layers=[4, 5, 2]
params_w, params_b = init(layers)
params_b

{'bias1': array([[ 0.14656488],
        [-0.02257763],
        [ 0.00675282],
        [-0.14247482],
        [-0.05443827]]), 'bias2': array([[-0.12208436],
        [ 0.02088636]])}

In [83]:
y_pred, activations, outputs = forward_pass(train_X, params_w, params_b, layers)

[[ 0.04967142 -0.01382643  0.06476885  0.15230299]
 [-0.02341534 -0.0234137   0.15792128  0.07674347]
 [-0.04694744  0.054256   -0.04634177 -0.04657298]
 [ 0.02419623 -0.19132802 -0.17249178 -0.05622875]
 [-0.10128311  0.03142473 -0.09080241 -0.14123037]]
[[ 0.04967142 -0.02341534 -0.04694744  0.02419623 -0.10128311]
 [-0.01382643 -0.0234137   0.054256   -0.19132802  0.03142473]
 [ 0.06476885  0.15792128 -0.04634177 -0.17249178 -0.09080241]
 [ 0.15230299  0.07674347 -0.04657298 -0.05622875 -0.14123037]]
[[ 0.01109226 -0.11509936  0.0375698  -0.06006387 -0.02916937]
 [-0.06017066  0.18522782 -0.00134972 -0.10577109  0.08225449]]
[[ 0.01109226 -0.06017066]
 [-0.11509936  0.18522782]
 [ 0.0375698  -0.00134972]
 [-0.06006387 -0.10577109]
 [-0.02916937  0.08225449]]


In [84]:
outputs

{'out1': array([[-0.41162856, -0.60688148,  0.52881383, -0.93400855,  0.62108388],
        [-1.12742848, -0.73861961,  1.02493951, -2.1282359 ,  1.41397605],
        [ 0.73337783,  0.33477858, -0.3007042 , -0.63949732, -0.84010936],
        ...,
        [-0.29795143, -0.62849651,  0.63496518, -1.64981754,  0.52474738],
        [ 0.11876579, -0.00660879,  0.01888744, -0.1281374 , -0.01079464],
        [-0.18150692, -0.64068089,  0.54361099, -1.31256102,  0.40377109]]),
 'out2': array([[-0.17054681,  0.08506513],
        [-0.15878761,  0.1199711 ],
        [-0.19524187,  0.07590903],
        ...,
        [-0.16084392,  0.09343343],
        [-0.19722292,  0.07204662],
        [-0.16321834,  0.08348033]])}